// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppMessage.proto

package com.github.dawndev.orion.core.proto;

public final class AppMessage {
  private AppMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.maple.network.proto.BaseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 code = 1;</code>
     *
     * <pre>
     * 消息码
     * </pre>
     */
    boolean hasCode();
    /**
     * <code>optional int32 code = 1;</code>
     *
     * <pre>
     * 消息码
     * </pre>
     */
    int getCode();

    /**
     * <code>optional bytes body = 2;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 2;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code com.maple.network.proto.BaseMessage}
   *
   * <pre>
   * 基本消息
   * </pre>
   */
  public static final class BaseMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.maple.network.proto.BaseMessage)
      BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BaseMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BaseMessage defaultInstance;
    public static BaseMessage getDefaultInstance() {
      return defaultInstance;
    }

    public BaseMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              code_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AppMessage.internal_static_com_maple_network_proto_BaseMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AppMessage.internal_static_com_maple_network_proto_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BaseMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<BaseMessage> PARSER =
        new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>optional int32 code = 1;</code>
     *
     * <pre>
     * 消息码
     * </pre>
     */
    public boolean hasCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 code = 1;</code>
     *
     * <pre>
     * 消息码
     * </pre>
     */
    public int getCode() {
      return code_;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 2;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes body = 2;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private void initFields() {
      code_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, body_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(BaseMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.maple.network.proto.BaseMessage}
     *
     * <pre>
     * 基本消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.maple.network.proto.BaseMessage)
        BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AppMessage.internal_static_com_maple_network_proto_BaseMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AppMessage.internal_static_com_maple_network_proto_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BaseMessage.class, Builder.class);
      }

      // Construct using com.maple.network.proto.AppMessage.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        code_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AppMessage.internal_static_com_maple_network_proto_BaseMessage_descriptor;
      }

      public BaseMessage getDefaultInstanceForType() {
        return BaseMessage.getDefaultInstance();
      }

      public BaseMessage build() {
        BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public BaseMessage buildPartial() {
        BaseMessage result = new BaseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.code_ = code_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BaseMessage) {
          return mergeFrom((BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BaseMessage other) {
        if (other == BaseMessage.getDefaultInstance()) return this;
        if (other.hasCode()) {
          setCode(other.getCode());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BaseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>optional int32 code = 1;</code>
       *
       * <pre>
       * 消息码
       * </pre>
       */
      public boolean hasCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 code = 1;</code>
       *
       * <pre>
       * 消息码
       * </pre>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 1;</code>
       *
       * <pre>
       * 消息码
       * </pre>
       */
      public Builder setCode(int value) {
        bitField0_ |= 0x00000001;
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 1;</code>
       *
       * <pre>
       * 消息码
       * </pre>
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 2;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes body = 2;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 2;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 2;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.maple.network.proto.BaseMessage)
    }

    static {
      defaultInstance = new BaseMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.maple.network.proto.BaseMessage)
  }

  public interface UdpMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.maple.network.proto.UdpMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 token = 1;</code>
     *
     * <pre>
     * 客户端token
     * </pre>
     */
    boolean hasToken();
    /**
     * <code>optional int32 token = 1;</code>
     *
     * <pre>
     * 客户端token
     * </pre>
     */
    int getToken();

    /**
     * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    BaseMessage getMsg();
    /**
     * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    BaseMessageOrBuilder getMsgOrBuilder();

    /**
     * <code>optional int32 msgIndex = 3;</code>
     *
     * <pre>
     * 消息序号
     * </pre>
     */
    boolean hasMsgIndex();
    /**
     * <code>optional int32 msgIndex = 3;</code>
     *
     * <pre>
     * 消息序号
     * </pre>
     */
    int getMsgIndex();
  }
  /**
   * Protobuf type {@code com.maple.network.proto.UdpMessage}
   *
   * <pre>
   * UDP 基本消息
   * </pre>
   */
  public static final class UdpMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.maple.network.proto.UdpMessage)
      UdpMessageOrBuilder {
    // Use UdpMessage.newBuilder() to construct.
    private UdpMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UdpMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UdpMessage defaultInstance;
    public static UdpMessage getDefaultInstance() {
      return defaultInstance;
    }

    public UdpMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UdpMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              token_ = input.readInt32();
              break;
            }
            case 18: {
              BaseMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = msg_.toBuilder();
              }
              msg_ = input.readMessage(BaseMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msg_);
                msg_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AppMessage.internal_static_com_maple_network_proto_UdpMessage_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AppMessage.internal_static_com_maple_network_proto_UdpMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UdpMessage.class, Builder.class);
    }

    public static com.google.protobuf.Parser<UdpMessage> PARSER =
        new com.google.protobuf.AbstractParser<UdpMessage>() {
      public UdpMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UdpMessage(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<UdpMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TOKEN_FIELD_NUMBER = 1;
    private int token_;
    /**
     * <code>optional int32 token = 1;</code>
     *
     * <pre>
     * 客户端token
     * </pre>
     */
    public boolean hasToken() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 token = 1;</code>
     *
     * <pre>
     * 客户端token
     * </pre>
     */
    public int getToken() {
      return token_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private BaseMessage msg_;
    /**
     * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    public BaseMessage getMsg() {
      return msg_;
    }
    /**
     * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    public BaseMessageOrBuilder getMsgOrBuilder() {
      return msg_;
    }

    public static final int MSGINDEX_FIELD_NUMBER = 3;
    private int msgIndex_;
    /**
     * <code>optional int32 msgIndex = 3;</code>
     *
     * <pre>
     * 消息序号
     * </pre>
     */
    public boolean hasMsgIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 msgIndex = 3;</code>
     *
     * <pre>
     * 消息序号
     * </pre>
     */
    public int getMsgIndex() {
      return msgIndex_;
    }

    private void initFields() {
      token_ = 0;
      msg_ = BaseMessage.getDefaultInstance();
      msgIndex_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, token_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, msg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, msgIndex_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, token_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, msg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, msgIndex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static UdpMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UdpMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UdpMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UdpMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UdpMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UdpMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static UdpMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static UdpMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static UdpMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static UdpMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(UdpMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.maple.network.proto.UdpMessage}
     *
     * <pre>
     * UDP 基本消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.maple.network.proto.UdpMessage)
        UdpMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AppMessage.internal_static_com_maple_network_proto_UdpMessage_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AppMessage.internal_static_com_maple_network_proto_UdpMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UdpMessage.class, Builder.class);
      }

      // Construct using com.maple.network.proto.AppMessage.UdpMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        token_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (msgBuilder_ == null) {
          msg_ = BaseMessage.getDefaultInstance();
        } else {
          msgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        msgIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AppMessage.internal_static_com_maple_network_proto_UdpMessage_descriptor;
      }

      public UdpMessage getDefaultInstanceForType() {
        return UdpMessage.getDefaultInstance();
      }

      public UdpMessage build() {
        UdpMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public UdpMessage buildPartial() {
        UdpMessage result = new UdpMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.token_ = token_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (msgBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = msgBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgIndex_ = msgIndex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UdpMessage) {
          return mergeFrom((UdpMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UdpMessage other) {
        if (other == UdpMessage.getDefaultInstance()) return this;
        if (other.hasToken()) {
          setToken(other.getToken());
        }
        if (other.hasMsg()) {
          mergeMsg(other.getMsg());
        }
        if (other.hasMsgIndex()) {
          setMsgIndex(other.getMsgIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        UdpMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (UdpMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int token_ ;
      /**
       * <code>optional int32 token = 1;</code>
       *
       * <pre>
       * 客户端token
       * </pre>
       */
      public boolean hasToken() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 token = 1;</code>
       *
       * <pre>
       * 客户端token
       * </pre>
       */
      public int getToken() {
        return token_;
      }
      /**
       * <code>optional int32 token = 1;</code>
       *
       * <pre>
       * 客户端token
       * </pre>
       */
      public Builder setToken(int value) {
        bitField0_ |= 0x00000001;
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 token = 1;</code>
       *
       * <pre>
       * 客户端token
       * </pre>
       */
      public Builder clearToken() {
        bitField0_ = (bitField0_ & ~0x00000001);
        token_ = 0;
        onChanged();
        return this;
      }

      private BaseMessage msg_ = BaseMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          BaseMessage, BaseMessage.Builder, BaseMessageOrBuilder> msgBuilder_;
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public BaseMessage getMsg() {
        if (msgBuilder_ == null) {
          return msg_;
        } else {
          return msgBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public Builder setMsg(BaseMessage value) {
        if (msgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msg_ = value;
          onChanged();
        } else {
          msgBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public Builder setMsg(
          BaseMessage.Builder builderForValue) {
        if (msgBuilder_ == null) {
          msg_ = builderForValue.build();
          onChanged();
        } else {
          msgBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public Builder mergeMsg(BaseMessage value) {
        if (msgBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              msg_ != BaseMessage.getDefaultInstance()) {
            msg_ =
              BaseMessage.newBuilder(msg_).mergeFrom(value).buildPartial();
          } else {
            msg_ = value;
          }
          onChanged();
        } else {
          msgBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public Builder clearMsg() {
        if (msgBuilder_ == null) {
          msg_ = BaseMessage.getDefaultInstance();
          onChanged();
        } else {
          msgBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public BaseMessage.Builder getMsgBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public BaseMessageOrBuilder getMsgOrBuilder() {
        if (msgBuilder_ != null) {
          return msgBuilder_.getMessageOrBuilder();
        } else {
          return msg_;
        }
      }
      /**
       * <code>optional .com.maple.network.proto.BaseMessage msg = 2;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          BaseMessage, BaseMessage.Builder, BaseMessageOrBuilder>
          getMsgFieldBuilder() {
        if (msgBuilder_ == null) {
          msgBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              BaseMessage, BaseMessage.Builder, BaseMessageOrBuilder>(
                  getMsg(),
                  getParentForChildren(),
                  isClean());
          msg_ = null;
        }
        return msgBuilder_;
      }

      private int msgIndex_ ;
      /**
       * <code>optional int32 msgIndex = 3;</code>
       *
       * <pre>
       * 消息序号
       * </pre>
       */
      public boolean hasMsgIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 msgIndex = 3;</code>
       *
       * <pre>
       * 消息序号
       * </pre>
       */
      public int getMsgIndex() {
        return msgIndex_;
      }
      /**
       * <code>optional int32 msgIndex = 3;</code>
       *
       * <pre>
       * 消息序号
       * </pre>
       */
      public Builder setMsgIndex(int value) {
        bitField0_ |= 0x00000004;
        msgIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 msgIndex = 3;</code>
       *
       * <pre>
       * 消息序号
       * </pre>
       */
      public Builder clearMsgIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgIndex_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.maple.network.proto.UdpMessage)
    }

    static {
      defaultInstance = new UdpMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.maple.network.proto.UdpMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maple_network_proto_BaseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_maple_network_proto_BaseMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maple_network_proto_UdpMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_maple_network_proto_UdpMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020AppMessage.proto\022\027com.maple.network.pr" +
      "oto\")\n\013BaseMessage\022\014\n\004code\030\001 \001(\005\022\014\n\004body" +
      "\030\002 \001(\014\"`\n\nUdpMessage\022\r\n\005token\030\001 \001(\005\0221\n\003m" +
      "sg\030\002 \001(\0132$.com.maple.network.proto.BaseM" +
      "essage\022\020\n\010msgIndex\030\003 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_maple_network_proto_BaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_maple_network_proto_BaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_maple_network_proto_BaseMessage_descriptor,
        new String[] { "Code", "Body", });
    internal_static_com_maple_network_proto_UdpMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_maple_network_proto_UdpMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_maple_network_proto_UdpMessage_descriptor,
        new String[] { "Token", "Msg", "MsgIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
