spring:
  application:
    name: orion-broker
#  profiles:
#    active:
#      - dev

orion:
  broker:
    tcp-port: 8011

netty:
  boss-thread-count: 1
  work-thread-count: 4

akka:
  system-name: GAME-WORLD
  role-name: broker
  port: 6000