<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <description>游戏通信、脚本等核心基础包</description>

    <parent>
        <groupId>com.github.dawndev.orion</groupId>
        <artifactId>orion-engine</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>orion-core</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>

        <!-- Akka Actor -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-actor_2.12</artifactId>
        </dependency>

        <!-- Akka SLF4J -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-slf4j_2.12</artifactId>
            <version>${akka.version}</version>
        </dependency>

        <!-- Akka Cluster Sharding -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-cluster-sharding_2.12</artifactId>
        </dependency>

        <!-- Akka Cluster Metrics -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-cluster-metrics_2.12</artifactId>
        </dependency>

        <!-- Akka Distributed Data -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-distributed-data_2.12</artifactId>
        </dependency>

        <!-- Akka Stream -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-stream_2.12</artifactId>
        </dependency>

        <!-- Akka HTTP -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-http_2.12</artifactId>
        </dependency>

        <!-- Akka HTTP Jackson -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-http-jackson_2.12</artifactId>
        </dependency>

        <!-- Akka HTTP Spray JSON -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-http-spray-json_2.12</artifactId>
        </dependency>

        <!-- Akka Remote -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-remote_2.12</artifactId>
        </dependency>

        <!-- Akka Discovery -->
        <dependency>
            <groupId>com.typesafe.akka</groupId>
            <artifactId>akka-discovery_2.12</artifactId>
        </dependency>
    </dependencies>
</project>